### ISSUE TITLE
Can't connect to Xpra

### ISSUE THREAD

**Issue by khoaakt** [os-js/osjs-xpra#3]
![image](https://user-images.githubusercontent.com/6000592/33439452-0987f6fc-d620-11e7-9a95-8a5af7313dc9.png)

**Comment by sirhypernova** [comment]
Hey, I get the same thing happening

**Comment by sirhypernova** [comment]
It just disconnects after connection

**Comment by andersevenrud** [comment]
@khoaakt What version of Xpra are you running ?

**Comment by andersevenrud** [comment]
This issue should be solved in the upcoming version from v3. I can't reproduce this locally anymore.

Since, v3 is on schedule, this version will be archived, and this issue closed.

New repo: https://github.com/os-js/osjs-xpra-package
